<a href="https://colab.research.google.com/github/kanan110205/iti-tiwari/blob/main/sunstone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x=2

In [ ]:
x

2

In [ ]:
type(x)

int

In [ ]:
y=3.5

In [ ]:
y

3.5

In [ ]:
type(y)



float

In [ ]:
a="python"
b= 2

In [ ]:
type(a)


str

In [ ]:
type(b)

int

In [ ]:
a=3
type(a)

int

In [ ]:
b=4.9998
type(b)


float

In [ ]:
c="iti"
type(c)


str

In [ ]:
a=int(input ("enter the no"))

enter the no11


In [ ]:
a= int(input("enter the no."))
if a<0:
  print("negative no")
  

enter the no.-2
negative no


In [ ]:
a=40
a=int(input("enter no"))
if a<40:
  print(" less ")
else:
    print("greater")

enter no43
greater


In [ ]:

a=int(input("enter the first no"))
b=int(input("enter the second no"))
c=int(input("enter the last no"))
if (a>b)and(a>c):
 print('a is greater')
elif (b>a)and(b>c):
  print("b is greater")

else:
 print("c is greater")


enter the first no4
enter the second no6
enter the last no8
c is greater


In [ ]:
import numpy as np
array =np.array([1,2,3,4])
print(array)
print(np. __version__)
from numpy.random import random
random()

[1 2 3 4]
1.22.4


0.93713973067304

In [ ]:
x=random()
if x > 0.8 :
  answer="greater than 1"
print(x)

print(answer)

0.9717484726017194
greater than 1


In [ ]:
x=random()
if x > 0.5 :
  answer="greater than 0.5"
else:
  answer="less than 0.5"
print(x)

print(answer)

0.3296736485596041
less than 0.5


In [ ]:
x=random()
if x < 0.5 :
  answer="less than 0.5"
  
else:
  if x >=0.5<=0.8:
    answer= "hii"
  else:
   answer="greater than 0.5"
print(x)

print(answer)

0.030515402280964277
less than 0.5


In [ ]:
i = 1
while i <= 3:
  print(i)
  i += 1


1
2
3


In [ ]:
i = 1
while i <= 10:
  print(i)
  i += 1


1
2
3
4
5
6
7
8
9
10


In [ ]:
i = 10
while i >= 1:
  print(i)
  i -= 1


10
9
8
7
6
5
4
3
2
1


In [ ]:
n = 5
fact = 1

for i in range(1, n+1):
	fact = fact * i


print(fact)


120


In [ ]:
n=int(input("enter the no"))
reverse=0
while n!=0:
  rem=n%10
  reverse=reverse*10 + rem
  n//=10
  print(reverse)


enter the no123
3
32
321


In [ ]:
n=int(input("enter the no"))
reverse=0
while n!=0:
  rem=n%10
  reverse=reverse*10 + rem
  n//=10
  print(reverse)


enter the no123
3
32
321


In [ ]:
for i in range(15):
  print("hello")

hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello
hello


In [ ]:
range(5)


range(0, 5)

In [ ]:
list(range(5))
# list is a mixed data type 

[0, 1, 2, 3, 4]

In [ ]:
list (range(1,4))

[1, 2, 3]

In [ ]:
# list is an type of array more specifically it is a tyoe of vector or data structure
# list can also be called as the type of the order sequence of the element or ordered set of element,
# order starts from zero and ends at 9---(in other programming language like R list is start from 1)
# list is the strange element for data type or used to store mixed data type and every thing is numerated

In [ ]:
x=[4,6,11,5,8]
print(x)
type(x)


[4, 6, 11, 5, 8]


list

In [ ]:
i=["iti",1,True,4.32,x]
print(i)

['iti', 1, True, 4.32, [4, 6, 11, 5, 8]]


In [ ]:
i=["iti",1,True,4.32,]
print(i)

['iti', 1, True, 4.32]


In [ ]:
a=[1,2,3,4,5]
b=[2.4,1.2]
c=['iti','butter']
d=[a,b,c]

print(d)

[[1, 2, 3, 4, 5], [2.4, 1.2], ['iti', 'butter']]


In [ ]:
y=list(range(1,11,2))
print(y)
x=list(range(2,11,2))
print(x)

[1, 3, 5, 7, 9]
[2, 4, 6, 8, 10]


In [ ]:
p=["a",'c']
p[1]



'c'

In [ ]:
len(p)

2

In [ ]:
p[-2]


'a'

In [ ]:
p[-2]=5
p

[5, 'c']

In [ ]:
import pandas as pd
path= "/spreadsheet - Sheet1.csv"
df=pd.read_csv(path)
df.head(3)

name  name.1  name.2
0     iti     iti     iti
1   kanan   kanan   kanan
2  butter  butter  butter

In [ ]:
#slicing
hii=['a','b','c','d','e','f','g','h','i','j','k']
hii



['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k']

In [ ]:
print(hii[:])
print(hii[2:])
print(hii[2:3])
print(hii[5:6])
print(hii[-2:3])
print(hii[-4:-3])
print(hii[::3])
print(hii[::-3])
print(hii[6:2:-1])

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k']
['c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k']
['c']
['f']
[]
['h']
['a', 'd', 'g', 'j']
['k', 'h', 'e', 'b']
['g', 'f', 'e', 'd']


In [ ]:
#tupple=immutable list or immutale sequence of values or cannot be changed
t1=(1,2,3,4)
print(t1)
print(t1 [3])
print(max(t1))
print(min(t1))

(1, 2, 3, 4)
4
4
1


In [ ]:
i=0
while(True):
   if i+1<5:
    i=i+1
    continue
    print(i+1,end='')
    if(i==30):
      break
      i=i+1

In [ ]:
#decimal to binary
def DecimalToBinary(num):
	
	if num >= 1:
		DecimalToBinary(num // 2)
	print(num % 2, end = '')
if __name__ == '__main__':
     
   
    dec_val =int(input("enter no"))
     
    
    DecimalToBinary(dec_val)

0101

In [ ]:
#np.reshape(*,*,'c')
#np.reshape(*,*,'f')
#np.array()


In [ ]:
import numpy as np
mydata=np.arange(0,20)
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
np.reshape(mydata,(5,4))# default is opposite in r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
MATR1=np.reshape(mydata,(5,4),order='c')
MATR1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
MATR2=np.reshape(mydata,(5,4),order='f')
MATR2

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [ ]:
r1=["my","name","is","iti"]
r2=["what","a","beautiful","day"]
r3=[1,2,3,4]
[r1,r2,r3]

[['my', 'name', 'is', 'iti'], ['what', 'a', 'beautiful', 'day'], [1, 2, 3, 4]]

In [ ]:
np.array([r1,r2,r3])
#just mean less than this unicode  characters in the string

array([['my', 'name', 'is', 'iti'],
       ['what', 'a', 'beautiful', 'day'],
       ['1', '2', '3', '4']], dtype='<U21')

In [ ]:
print(np.array([r1,r2,r3]))

[['my' 'name' 'is' 'iti']
 ['what' 'a' 'beautiful' 'day']
 ['1' '2' '3' '4']]


In [ ]:
MATR1[2,2]

10

#what is happening here when i run this we've just created an object which is called a dictonary and it's kind of like a list ,but the difference is that a list is an ordered set of element whereas a dictonary is not orederd .it's got the key so therefore they are refrence by key
#the way to access element is using their key. so basically the key is kind of like the label of each value.




```
# This is formatted as code
```



In [ ]:
#dictonary 
dict1={'key1':'val1','key2':'val2','key3':'val3'}
dict1

{'key1': 'val1', 'key2': 'val2', 'key3': 'val3'}

In [ ]:
year=["2005-06","2006-07","2007-08","2008-08","2009-10","2010-11","2011-12","2012-13","2013-14","2014-15"]
gp=["79","76","75","81","76","79","82","76","77","69"]
mgp=["42.5","40.9","40.4","37.5",]

In [ ]:
import pandas as pd
data=pd.Series([0.25,0.4,0.32,0.45],index=['a','b','c','d'])
data

a    0.25
b    0.40
c    0.32
d    0.45
dtype: float64

In [ ]:
list(data.items())

[('a', 0.25), ('b', 0.4), ('c', 0.32), ('d', 0.45)]